[package]
name = "vedas_utils"
version = "0.1.0"
authors = ["mrrbrilliant <mrrbrilliantwork@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD:sdk/Cargo.toml
vedas_core = {path = "../vedas-core"}

=======
>>>>>>> origin/brilliant:vedas-utils/Cargo.toml
